- name: rabbitmq server configuration
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: copy rabbitmq repo
    
  - name: install rabbitmq server
    ansible.builtin.dnf:
        name: rabbitmq-server
        state: present 