- name: creating ec2 and r53 records
  hosts: all #inventory file use cheyakunda
  connection: local
  vars:
    sg_id: sg-0fd4180ae5446c35c
    ami_id: ami-0220d79f3f480ecf5
    domain_name: gaddam.online
    instances:
    - mongodb
    - catalogue
    env: dev
    action: create
  tasks:
    ### creation ##
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_groups: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"    
    register: ec2_output
    when: action == "create"


  - name: print output
    ansible.builtin.debug:
       msg: "{{ ec2_output }}"  
    when: action == "create"

  - name: create route r53
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #mongodb-dev.gaddam.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"  # list
    when: action == "create"

  - name: create route r53 for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" #roboshop-dev.gaddam.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_output.results }}" 
    when: #and
    - item.item == "frontend"
    - action == "create"


    ### Destroy ###
  - name: delete r53 records
    amazon.aws.route53: 
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}-{{ env }}.{{ domain_name }}" #roboshop-dev.gaddam.online
      type: A
      ttl: 1
    loop: "{{ instances }}"
    when: action == "destroy"
  
  - name: delete ec2 instance
    amazon.aws.ec2_instance:
       state: absent
       name: "{{ item }}-{{ env }}"
       wait: false
    loop: "{{ instances }}"
    when: action == "destroy"    



